eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    

spring:
  application:
    name: API-GATEWAY

  cloud:
    
   gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "http://localhost:3000"
              allowedMethods: "*"
              allowedHeaders: "*" 
      routes:
     
      - id: JOBSEEKER-SERVICE
        uri: http://localhost:7672
        predicates:
        - Path=/jobseeker/**
        filters:
           - AuthenticationFilter
           
      - id: RECRUITER-SERVICE
        uri: http://localhost:7673
        predicates:
        - Path=/recruiter/**
        filters:
           - AuthenticationFilter
           
      - id: JOB-SERVICE
        uri: http://localhost:8020
        predicates:
        - Path=/jobservice/**
        filters:
           - AuthenticationFilter
      
        
       
        
   
#okta:
#  oauth2:
#    issuer: https://dev-14013156.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oa9bp13lt1X7hRhb5d7
#    client-secret: bRmHaVNwL23j71bqtWgQmuM-gAjAaCmxWqsoFdQ-
#    scopes: openid, profile, email, offline_access 

          
     
  

server:
  port: 8062
  

    
    
  
    


  

    

  