eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    

spring:
  application:
    name: API-GATEWAY

  cloud:
    
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
       
#        
#      - id: PRODUCT-SERVICE
#        uri:
#          lb://PRODUCT-SERVICE/
#        predicates:
#        - Path=/product/**
#        filters:
#        - name: CircuitBreaker
#          args:
#            name: PRODUCT-SERVICE
#            fallbackuri: forward:/productServiceFallBack
#      
#      - id: ORDER-SERVICE
#        uri:
#          lb://ORDER-SERVICE/
#        predicates:
#        - Path=/order/**
#        filters:
#        - name: CircuitBreaker
#          args:
#            name: ORDER-SERVICE
#            fallbackuri: forward:/orderServiceFallBack
#      - id: PAYMENT-SERVICE
#        uri:
#          lb://PAYMENT-SERVICE/
#        predicates:
#        - Path=/payment/**
#        filters:
#        - name: CircuitBreaker
#          args:
#            name: PAYMENT-SERVICE
#            fallbackuri: forward:/paymentServiceFallBack
      - id: JOBSEEKERSERVICE
        uri:
          lb://JOBSEEKERSERVICE/
        predicates:
        - Path=/jobseeker/**
        filters:
        - name: CircuitBreaker
          args:
            name: JOBSEEKERSERVICE
            fallbackuri: forward:/jobSeekerServiceFallBack
      - id: RECRUITERSERVICE
        uri:
          lb://RECRUITERSERVICE/
        predicates:
        - Path=/recruiter/**
        filters:
        - name: CircuitBreaker
          args:
            name: RECRUITERSERVICE
            fallbackuri: forward:/recruiterServiceFallBack
      - id: JOBSERVICE
        uri:
          lb://JOBSERVICE/
        predicates:
        - Path=/jobservice/**
        filters:
        - name: CircuitBreaker
          args:
            name: JOBSERVICE
            fallbackuri: forward:/jobServiceFallBack
      - id: SECURITY-SERVICE
        uri:
          lb://SECURITY-SERVICE/
        predicates:
        - Path=/api/auth/**
        filters:
        - name: CircuitBreaker
          args:
            name: SECURITY-SERVICE
            fallbackuri: forward:/securityServiceFallBack
        
       
        
   
#okta:
#  oauth2:
#    issuer: https://dev-14013156.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oa9bp13lt1X7hRhb5d7
#    client-secret: bRmHaVNwL23j71bqtWgQmuM-gAjAaCmxWqsoFdQ-
#    scopes: openid, profile, email, offline_access 

          
     
  

server:
  port: 8062
  

    
    
  
    


  

    

  